<?

/**
 * Implementation of hook_init() to change a hard coded ugly core string
 */
function haxeflixel_site_init () {
    if ( isset( $_SESSION[ 'messages' ] ) ) {

        $targetm = "A welcome message with further instructions has been sent to your e-mail address.";
        $newMessage = "Thankyou for registering, please see the confirmation email we have just sent you.";

        if ( is_array ( $_SESSION[ 'messages' ] ) ) {
            foreach ( $_SESSION[ 'messages' ] as $type => $messages ) {
                foreach ( $messages as $key => $message ) {
                    if ( $type == "status" && $message == $targetm )
                        $_SESSION[ 'messages' ][ 'status' ][ $key ] = $newMessage;
                }
            }
        }
    }
}


/**
 * Implementation of hook_wysiwyg_editor_settings_alter()
 */
function haxeflixel_site_wysiwyg_editor_settings_alter(&$settings, $context) {
    if ($context['profile']->editor == 'tinymce') {
      $settings['forced_root_block'] = FALSE;
      $settings['force_br_newlines'] = TRUE;
      $settings['force_p_newlines'] = FALSE;
    }
    
}





function test () {
    

}