<?

/**
 * Implementation of hook_init() to change a hard coded ugly core string
 */
function haxeflixel_site_init () {
    if ( isset( $_SESSION[ 'messages' ] ) ) {

        $targetm = "A welcome message with further instructions has been sent to your e-mail address.";
        $newMessage = "Thankyou for registering, please see the confirmation email we have just sent you.";

        if ( is_array ( $_SESSION[ 'messages' ] ) ) {
            foreach ( $_SESSION[ 'messages' ] as $type => $messages ) {
                foreach ( $messages as $key => $message ) {
                    if ( $type == "status" && $message == $targetm )
                        $_SESSION[ 'messages' ][ 'status' ][ $key ] = $newMessage;
                }
            }
        }
    }
}

function test () {


}


/*//use custom modal and ajax to grab submit handler etc
//http://haxedev/media/browser?render=media-popup